/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package employeemanage;

import employeemanage.Client;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ADMIN
 */
public class AdminLogin extends javax.swing.JFrame {

    /**
     * Creates new form AdminLogin
     */
    public AdminLogin() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jBtnPayroll = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jBtnWorkProgress = new javax.swing.JButton();
        jBtnAssignment = new javax.swing.JButton();
        jBtnEmployeeList = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jlbLogOutAdmin = new javax.swing.JLabel();
        btnChat = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/money-bag.png"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(470, 170, 130, 120);

        jBtnPayroll.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBtnPayroll.setForeground(new java.awt.Color(0, 153, 255));
        jBtnPayroll.setText("Working");
        jBtnPayroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPayrollActionPerformed(evt);
            }
        });
        jPanel2.add(jBtnPayroll);
        jBtnPayroll.setBounds(250, 310, 150, 29);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Group-icon.png"))); // NOI18N
        jPanel2.add(jLabel3);
        jLabel3.setBounds(60, 180, 130, 120);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/assignment.png"))); // NOI18N
        jPanel2.add(jLabel4);
        jLabel4.setBounds(660, 170, 130, 130);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/software-developer (1).png"))); // NOI18N
        jPanel2.add(jLabel5);
        jLabel5.setBounds(260, 170, 140, 130);

        jBtnWorkProgress.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBtnWorkProgress.setForeground(new java.awt.Color(0, 153, 255));
        jBtnWorkProgress.setText("Work progress");
        jBtnWorkProgress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnWorkProgressActionPerformed(evt);
            }
        });
        jPanel2.add(jBtnWorkProgress);
        jBtnWorkProgress.setBounds(450, 310, 150, 29);

        jBtnAssignment.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBtnAssignment.setForeground(new java.awt.Color(0, 153, 255));
        jBtnAssignment.setText("Assignment");
        jBtnAssignment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAssignmentActionPerformed(evt);
            }
        });
        jPanel2.add(jBtnAssignment);
        jBtnAssignment.setBounds(660, 310, 150, 29);

        jBtnEmployeeList.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBtnEmployeeList.setForeground(new java.awt.Color(0, 153, 255));
        jBtnEmployeeList.setText("Employee List");
        jBtnEmployeeList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEmployeeListActionPerformed(evt);
            }
        });
        jPanel2.add(jBtnEmployeeList);
        jBtnEmployeeList.setBounds(50, 310, 150, 29);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 51, 51));
        jLabel6.setText("EMPLOYEE MANAGE");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(260, 50, 390, 100);

        jlbLogOutAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/log-out.png"))); // NOI18N
        jlbLogOutAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbLogOutAdminMouseClicked(evt);
            }
        });
        jPanel2.add(jlbLogOutAdmin);
        jlbLogOutAdmin.setBounds(780, 20, 40, 40);

        btnChat.setText("Chat");
        btnChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChatActionPerformed(evt);
            }
        });
        jPanel2.add(btnChat);
        btnChat.setBounds(710, 100, 72, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/backgroud.png"))); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(-100, -20, 940, 450);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 826, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnPayrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPayrollActionPerformed
        // TODO add your handling code here:
        Working pay= new Working();
        pay.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBtnPayrollActionPerformed

    private void jBtnWorkProgressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnWorkProgressActionPerformed
        // TODO add your handling code here:
        WorkProgress workProgress= new WorkProgress();
        workProgress.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBtnWorkProgressActionPerformed

    private void jBtnAssignmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAssignmentActionPerformed
        // TODO add your handling code here:
        Assignment assignment= new Assignment();
        assignment.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBtnAssignmentActionPerformed

    private void jBtnEmployeeListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEmployeeListActionPerformed
        // TODO add your handling code here:
        Manage mn= new Manage();
        mn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBtnEmployeeListActionPerformed

    private void jlbLogOutAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbLogOutAdminMouseClicked
        // TODO add your handling code here:
        Login lg= new Login();
        lg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jlbLogOutAdminMouseClicked

    private void btnChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChatActionPerformed
        // TODO add your handling code here:
        Client client = null;
        try {
            client = new Client("Hồ Hải Châu");
        } catch (IOException ex) {
            Logger.getLogger(AdminLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
        Thread t = new Thread(client);
        t.start();

        client.setVisible(true);
    }//GEN-LAST:event_btnChatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChat;
    private javax.swing.JButton jBtnAssignment;
    private javax.swing.JButton jBtnEmployeeList;
    private javax.swing.JButton jBtnPayroll;
    private javax.swing.JButton jBtnWorkProgress;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jlbLogOutAdmin;
    // End of variables declaration//GEN-END:variables
}
