/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package employeemanage;

import database.clsConnectDB;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ADMIN
 */
public class EmployeeLogin extends javax.swing.JFrame {

    String nameEmployee = "";

    /**
     * Creates new form EmployeeLogin
     */
    public EmployeeLogin() {
        initComponents();

    }
    private String IdEmLogin;

    public EmployeeLogin(String IdName) {
        initComponents();
        setLocationRelativeTo(null);
        this.IdEmLogin = IdName;
        jTxtAccount.setText(String.valueOf(IdEmLogin));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jBtnAssignedWork = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jBtnInformation = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jlbLogOutAdmin = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jBtnPayroll1 = new javax.swing.JButton();
        jTxtAccount = new javax.swing.JTextField();
        btnChat = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/id-card.png"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(610, 150, 130, 150);

        jBtnAssignedWork.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBtnAssignedWork.setForeground(new java.awt.Color(0, 153, 255));
        jBtnAssignedWork.setText("Assigned work");
        jBtnAssignedWork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAssignedWorkActionPerformed(evt);
            }
        });
        jPanel2.add(jBtnAssignedWork);
        jBtnAssignedWork.setBounds(340, 310, 150, 29);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/user-experience.png"))); // NOI18N
        jPanel2.add(jLabel5);
        jLabel5.setBounds(360, 150, 130, 140);

        jBtnInformation.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBtnInformation.setForeground(new java.awt.Color(0, 153, 255));
        jBtnInformation.setText("Information");
        jBtnInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnInformationActionPerformed(evt);
            }
        });
        jPanel2.add(jBtnInformation);
        jBtnInformation.setBounds(600, 310, 150, 29);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 51, 51));
        jLabel6.setText("EMPLOYEE INTERFACE");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(250, 40, 400, 100);

        jlbLogOutAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/log-out.png"))); // NOI18N
        jlbLogOutAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbLogOutAdminMouseClicked(evt);
            }
        });
        jPanel2.add(jlbLogOutAdmin);
        jlbLogOutAdmin.setBounds(780, 20, 40, 40);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/calendar.png"))); // NOI18N
        jPanel2.add(jLabel7);
        jLabel7.setBounds(130, 160, 130, 130);

        jBtnPayroll1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBtnPayroll1.setForeground(new java.awt.Color(0, 153, 255));
        jBtnPayroll1.setText("Attendance ");
        jBtnPayroll1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPayroll1ActionPerformed(evt);
            }
        });
        jPanel2.add(jBtnPayroll1);
        jBtnPayroll1.setBounds(120, 310, 150, 29);

        jTxtAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtAccountActionPerformed(evt);
            }
        });
        jPanel2.add(jTxtAccount);
        jTxtAccount.setBounds(30, 20, 100, 22);

        btnChat.setText("Chat");
        btnChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChatActionPerformed(evt);
            }
        });
        jPanel2.add(btnChat);
        btnChat.setBounds(710, 80, 72, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Downloads\\backgroud.png")); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(0, -20, 830, 440);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 826, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnAssignedWorkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAssignedWorkActionPerformed
        // TODO add your handling code here:
        AssignedWork assignedWork = new AssignedWork(IdEmLogin);
        assignedWork.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBtnAssignedWorkActionPerformed

    private void jBtnInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnInformationActionPerformed
        // TODO add your handling code here:
        Information inf = new Information(IdEmLogin);
        inf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBtnInformationActionPerformed

    private void jBtnPayroll1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPayroll1ActionPerformed
        // TODO add your handling code here:
        Attendance att = new Attendance(IdEmLogin);
        att.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBtnPayroll1ActionPerformed

    private void jlbLogOutAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbLogOutAdminMouseClicked
        // TODO add your handling code here:
        Login lg = new Login();
        lg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jlbLogOutAdminMouseClicked

    private void jTxtAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtAccountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtAccountActionPerformed

    private void btnChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChatActionPerformed
        // TODO add your handling code here:

        clsConnectDB connect = new clsConnectDB();
        ResultSet rs = connect.ExcuteQueryGetTable("select * from NhanVien");
        try {
            while (rs.next()) {
                   if(IdEmLogin.equals(rs.getString("ID"))){
                       System.out.println("id" + IdEmLogin);
                       nameEmployee = rs.getString(2);
                       break;
                   }
                   System.out.println("Name nv" + nameEmployee);
            }
        } catch (SQLException ex) {
            Logger.getLogger(EmployeeLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        Client client = null;
        try {
            client = new Client(nameEmployee);
        } catch (IOException ex) {
            Logger.getLogger(EmployeeLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
        Thread t = new Thread(client);
        t.start();

        client.setVisible(true);


    }//GEN-LAST:event_btnChatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChat;
    private javax.swing.JButton jBtnAssignedWork;
    private javax.swing.JButton jBtnInformation;
    private javax.swing.JButton jBtnPayroll1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTxtAccount;
    private javax.swing.JLabel jlbLogOutAdmin;
    // End of variables declaration//GEN-END:variables
}
